### ISSUE TITLE
Option to configure path to soy jar?

### ISSUE THREAD

**Issue by bendman** [Medium/soynode#49]
The jar file used to compile soy references your `closure-templates` module, but this doesn't work if individuals need to reference a particular version of the soy jar for compilation.  If there was an option (via `setOptions`) for the location of the soy jar, the `closure-templates` version could be the default.

**Comment by nicks** [comment]
the soy compiler api changes a lot between releases. how would you ensure that the jar was compatible with the soynode version? I feel like most pairings between soynode and jar would be broken, and wouldn't work in practice.

Can you elaborate a bit more on why you need to reference a particular version of the soy jar?

**Comment by bendman** [comment]
In our case it's because the version of Java (6) running on some target machines can't be upgraded, and the version used in soynode won't run on any target versions under 7.  We are using an older soy compiler for that. We also have customized the compiler we use with our own helpers.

**Comment by nicks** [comment]
it might be simpler for you to just fork soynode to soynode-java6 or
whatever?

notice that would also need to inject your own soyutils support js.

**Comment by bendman** [comment]
We managed to just create a private version of the closure-templates package, then resolve it with the following code in our package.json:
```
{
  "devDependencies": {
    "closure-templates": "./private_modules/closure-templates"
  ...
}
```
Then our closure-templates package could just return the custom path to our jar file, and soynode and soy-loader would resolve to our version.
