### ISSUE TITLE
Project Name is too feminine

### ISSUE THREAD

**Issue by IronmanDiesForeverAtCloseOfEndgame** [Medium/soynode#72]
I have no desire to use software with names like, "soynode" or "estrogenpython". Please stop.

**Comment by majelbstoat** [comment]
🙄 You're obviously a troll, and this doesn't even deserve a response, but for the benefit of others who are curious about the name:

* soy was the internal name of google's closure templates. soy is the file extension for those templates. This is the node library for soy. Hence soynode.
* The name long predates whatever meaning it's come to have among incels.
* The idea that software development is exclusively masculine is idiotic, and incorrect.
